services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./storage/app/public:/var/www/storage/app/public
            - ./public/storage:/var/www/public/storage
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: php artisan serve --host=0.0.0.0 --port=8000
        networks:
            - laravel


    artisan:
        image: php:8.2-cli
        container_name: artisan
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        entrypoint: ["php"]
        networks:
            - laravel

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_DATABASE: Ideas_db
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: laravel_phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
